import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    const [buttonUsed, setButtonUsed] = useState(false)

    return (
        <div className="scroll-smooth">
            <Head>
                <title>Test Page | Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-auto flex flex-col gap-y-12 h-screen justify-between text-center">
                <blockquote className="text-2xl font-semibold italic text-center text-white py-24">
                    When you look
                    <span className="before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-slate-600 relative inline-block">
                        <span className="relative text-white">annoyed</span>
                    </span>
                    all the time, people think that you're busy.
                </blockquote>

                <div>
                    <h1 className="text-4xl mt-24 mb-12">
                        Stay a while and listen!
                    </h1>
                    <div
                        className={
                            buttonUsed
                                ? 'invisible'
                                : 'rotate-90 hover:cursor-pointer'
                        }
                        onClick={() => {
                            window.scrollTo({
                                top: document.body.scrollHeight,
                                behavior: 'smooth',
                            })
                            setButtonUsed(true)
                        }}
                    >
                        <span className="text-4xl text-slate-600 block bounce">
                            &raquo;
                        </span>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home
